assetPath="./assets"
toolPath="./D4DJ-Tool-bin/D4DJ-Tool.dll"
extractorPath="./D4DJ-asset-extractor-bin/D4DJAssetExtractor.dll"
crawlerPool=15
assetServerPath='https://example.com'
vgmStreamPath="./vgmstream/test.exe"
ffmpegPath="./ffmpeg.exe"

#If upload to aws
[aws]
accessKey=""
secretKey=""
bucketName=""
region=""
baseDir="jp/"